### ISSUE TITLE
Wrong back button behavior

### ISSUE THREAD

**Issue by v1nc** [hezedu/history-navigation-vue#1]
The back button behaves wrong, at least on android 11 with latest chrome.

Steps to reproduce:
1. Visit [Example Page](https://hezedu.github.io/history-navigation-vue/examples.html) and open Hello World Example
2. Click on _To Detail_
3. Click on _Back_
4. Click android back button or use back gesture

Expected Behaviour: 
The last website you visited is loaded.

Actual Behaviour:
Nothing happens. You need to use the back button again to trigger the expected behaviour.

The same happens when you use the back button after clicking _To Detail_

**Comment by hezedu** [comment]
Thank you for your feedback.

**Comment by hezedu** [comment]
Remove `onExit` option(hotfix). replace with `backAgainToExit` option on v1.4.0, And fixed this BUG. Thanks again.
